apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: podini
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podini
  namespace: podini
rules:
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - list
  - get
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podini
  namespace: podini
subjects:
- kind: User
  name: podini
roleRef:
  kind: Role
  name: podini
  apiGroup: rbac.authorization.k8s.io


