apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-tosimple
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage: 
    size: 1Gi
  monitoring:
    enablePodMonitor: true
