apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 443
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: cert-volume
          mountPath: /etc/nginx/certs
          readOnly: true
        args:
        - /bin/sh
        - -c
        - |
          cat <<EOF > /etc/nginx/nginx.conf
          events {}
          http {
            server {
              listen 443 ssl;
              ssl_certificate /etc/nginx/certs/tls.crt;
              ssl_certificate_key /etc/nginx/certs/tls.key;
              ssl_verify_client on;
              ssl_client_certificate /etc/nginx/certs/ca.crt;
              location / {
                return 200 'Hello, Secure World!';
              }
            }
          }
          EOF
          nginx -g 'daemon off;'
      volumes:
      - name: cert-volume
        secret:
          secretName: server-cert-secret
