commonLabels: 
  hallo: welt
generatorOptions:
  disableNaueSuffixHash: true # Brauchen wir auf jeden Fall (ok eh default) weil volumes idempotent ist)
  annotations:
    iwas: here
configMapGenerator:
- name: index
  files:
  - index.html
  - mama.html
resources:
- www-configmap-svc.yml
- deployment.yaml
