commonLabels: 
  hallo: welt
generatorOptions:
  disableNameSuffixHash: true # Wird eigentlich hier nicht gebraucht sondern, wenn eine spezielle Configmap erstellt wird
  annotations:
    iwas: here
configMapGenerator:
- name: index
  files:
  - index.html
  - mama.html
resources:
- www-configmap-svc.yml
- deployment.yaml
