apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: argo-example-drift
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: www
  minReplicas: 5
  maxReplicas: 8
#  metrics:
#  - type: Pods
#    pods:
#      metric:
#        name: erkan_queue_length
#      target:
#        type: AverageValue
#        averageValue: 5
