apiVersion: v1
kind: Pod
metadata:
  name: notignored
  namespace: argo-example-drift
  labels:
    fluxcd: ahoi
spec:
 timeoutSeconds: 1
  containers:
  - name: meinserver
    image: erkules/nginxhostname:v1
    ressources:
      requests:
        memorry: "5M"
    




