apiVersion: v1
kind: Pod
metadata:
  name: ignored
  namespace: argo-example-drift
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname:v1
    ports:
    - name:          nicht-notwendig
      containerPort: 80
    - name:          nerv #prometheus-operator will benamste Ports
      containerPort: 8080
    




