apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: selfsigned-ca-trust
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: server-cert-secret
      key: ca.crt
  target:
    configMap:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: trustmanager-selfsigned

# namespaceSelector still needs to read the secrets from a 'trusted Namespace' https://github.com/cert-manager/trust-manager/issues/131 to the rescure (namspaced bundles) 

