kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  #image: kindest/node:v1.22.1
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
- role: worker
  #image: kindest/node:v1.22.1
- role: worker
  #image: kindest/node:v1.22.1
- role: worker
  #  image: kindest/node:v1.22.1
