kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
- role: worker
- role: worker
  #- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
# Eigenes CNI applyen
## CALICO
#kubectl apply --server-side -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/tigera-operator.yaml
#kubectl apply --server-side -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/custom-resources.yaml

# NOPE:kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
