apiVersion: apps/v1
kind: Deployment
metadata:
  {{/*  mit inculde greifen wir auf das fullname template zu (siehe _helpers.tpl) */}}
  name: {{ include "simple.fullname" . }}
spec:
  {{/* replicaCount bekommen wir aus der values.yaml. Wir haben mal einen Default gesetzt :) */}}
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
    {{/* Einfach lassen ist aus _helpers.tpl */}}
      {{- include "simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
