# Simple example
# list of Pods
# Check -> Controller4Pods
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: boring
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Boring        # Kinda sucks but == .metadata.name as best practice
    spec:
      # Spec fields that users can provide.
      name: string

  # Define the resources this API will manage.
  resources:
    - id: pod1
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          name: ${schema.spec.name}-pod1 # Use the name provided by user
        spec:
          containers:
            - name: ${schema.spec.name}
              image: nginx:alpine
    - id: pod2
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          name: ${schema.spec.name}-pod2 # Use the name provided by user
        spec:
          containers:
            - name: ${schema.spec.name}
              image: nginx:alpine

