apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-mockup
spec:
  scaleTargetRef:
    name:          nixda
  pollingInterval: 10 
  cooldownPeriod:  300
  minReplicaCount: 3 
  maxReplicaCount: 10
#  advanced:                           
#    restoreToOriginalReplicaCount: true
#    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
#      behavior:                                      # Optional. Use to modify HPA's scaling behavior
#        scaleDown:
#          stabilizationWindowSeconds: 300
#          policies:
#          - type: Percent
#            value: 100
#            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      # Required fields:
      serverAddress: http://prometheus-operated.monitoring:9090
      metricName: erkan_queue_length
      query: sum(erkan_queue_length)
      threshold: '5'

