---
apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mutating
  namespace: webhook
data:
  index.html: |
    #!/bin/bash 
    echo Status: 200 OK
    echo Content-Type: application/json
    echo        
    echo        
    post="$(cat)"
    echo  $post >&2
    echo  $post >/tmp/log
    ID=$(echo $post | jq -r .request.uid )
    echo $ID >/tmp/id
    jq -n --arg id "$ID" '{ "apiVersion": "admission.k8s.io/v1", kind: "AdmissionReview", "response": { "uid": $id, "allowed": true, "patchType": "JSONPatch", "patch": "Wwp7CiJvcCI6ICJhZGQiLAoicGF0aCI6ICIvbWV0YWRhdGEvYW5ub3RhdGlvbnMvaGFsbG8iLAoidmFsdWUiOiAid2VsdCIKfQpdCg==" }  }'


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating
  namespace: webhook
spec:
  replicas: 1
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mutating
  template:
    metadata:
      name: mutating
      labels:
        app: mutating
    spec:
      containers:
      - name: image1
        image: erkules/webhookimg:v3
        volumeMounts:
        - name: mutating
          mountPath: /usr/local/apache2/htdocs
        imagePullPolicy: IfNotPresent
      volumes:
      - name: mutating
        configMap:
          defaultMode:  0777
          name: mutating 

---

apiVersion: v1
kind: Service
metadata:
  name: mutating
  namespace: webhook
spec:
  ports:
  - port: 443
  selector:
    app: mutating

