apiVersion: linsenraum.de/v1alpha1
kind: Appenzeller
metadata:
  name: emmentaler
spec:
  anzahl: 3
  # Wenn wir mehrere Compositions haben
  # crossplane:
  #   compositionRef:
  #     name: .....
  #  vs.
  # compositionSelector:
  #   matchLabels:
  #     environment: production
