# Optional nicht zu verstehen nur um nicht mit einem zufälligen ServiceaccountNamen zu arbeiten
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
---
# Optional nicht zu verstehen nur um nicht mit einem zufälligen ServiceaccountNamen zu arbeiten
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-kubernetes
          containers:
            - name: package-runtime
---
# Installiert entsprechenden Conteroller
# https://marketplace.upbound.io/providers
# OCI-Packet: Controller/CRDs
# Wichtig
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v1.0.0
  runtimeConfigRef:
    name: provider-kubernetes-runtime
---
# Optional nicht zu verstehen nur um nicht mit einem zufälligen ServiceaccountNamen zu arbeiten
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-kubernetes
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes
    namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
# Wichtig
# Davon kann es mehrere geben
# Aber mit Namespaced Objects machen wir eine ClusterProviderConfig
#apiVersion: kubernetes.crossplane.io/v1alpha1  
#kind: ProviderConfig
#metadata:
#  name: kubernetes-intern
#spec:
#  credentials:
#    source: InjectedIdentity
---
apiVersion: kubernetes.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: kubernetes-intern
spec:
  credentials:
    source: InjectedIdentity
