apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xappenzellers.linsenraum.de
spec:
  # Ab Crossplane v2
  scope: Namespaced
  # Name der Ressource (XR)
  group: linsenraum.de
  names:
    kind: XAppenzeller
    plural: xappenzellers
  # Mit v2 weg
  #claimNames:
  #  kind: Apppenzeller
  #  plural: appenzellers
  #
  #  Die API-Versionen und das Schema (die erlaubten Parameter)
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                anzahl:
                  type: integer
                  description: Replicationszahl
              required:
                - anzahl
