apiVersion: kyverno.io/v1
kind: Policy    
metadata:       
  name: check-node-port
spec:           
  validationFailureAction: Enforce
  rules:        
  - name: check-node-port
    match:      
      resources:
        kinds:  
        - Service
    validate:   
      # Pattern muss erfüllt sein  <-- WICHTIG!eins11
      message: "NodePort type is not allowed"
      pattern:  
        spec:   
          type: !NodePort

