#https://kyverno.io/policies/cleanup/cleanup-bare-pods/cleanup-bare-pods/
#Achtung der kyverno:cleanup-controller braucht mehr rechte
apiVersion: kyverno.io/v2
kind: CleanupPolicy
metadata:
  name: clean-bare-pods
spec:
  match:
    any:
    - resources:
        kinds:
        - Pod
  conditions:
    all:
    - key: "{{ target.metadata.ownerReferences[] || `[]` }}"
      operator: Equals
      value: []
  schedule: "*/5 * * * *"

