apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.kyverno.io/aggregate-to-cleanup-controller: "true"
  name: kyverno:cleanup-controller-pods
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - delete
  - list
