apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: policy-add-annotations
spec:
  #mutateExistingOnPolicyUpdate: true  # Wollen wir existierende updaten brauchts auch .mutate.targets!
  rules:
  - name: "add annotations"
    match:
      resources:
        kinds:
        - Pod
    mutate:   #<--- Jaja MUTATION
      patchStrategicMerge:
        metadata:
          annotations:
            iwas: here
    
