apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: hallo
  namespace: default
  labels:
    tenant.clastix.io: hallo
spec:
  dataStore: default
  controlPlane:
    deployment:
      replicas: 1
      additionalMetadata:
        labels:
          tenant.clastix.io: hallo
      extraArgs:
        apiServer: []
        controllerManager: []
        scheduler: []
      resources:
        apiServer:
          requests:
            cpu: 250m
            memory: 512Mi
          limits: {}
        controllerManager:
          requests:
            cpu: 125m
            memory: 256Mi
          limits: {}
        scheduler:
          requests:
            cpu: 125m
            memory: 256Mi
          limits: {}
    service:
      additionalMetadata:
        labels:
          tenant.clastix.io: hallo
      serviceType: ClusterIP
        #serviceType: NodePort
  kubernetes:
    version: v1.28.0
    kubelet:
      cgroupfs: systemd
      preferredAddressTypes:
        - InternalIP
        - ExternalIP
        - Hostname
    admissionControllers:
      - ResourceQuota
      - LimitRanger
  networkProfile:
    port: 30000
    certSANs:
    - hallo.zwerk.org
    serviceCidr:  10.96.0.0/16
    podCidr: 10.36.0.0/16
    dnsServiceIPs:
    - 10.96.0.10
    allowAddressAsExternalIP: true
    address: 135.181.95.102 
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity: {}
