apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podmania
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - podname: hallo
        namespace: welt
      - podname: hallo
        namespace: geld
      - podname: jajaja
        namespace: welt
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: my-project
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        server: https://kubernetes.default.svc
        namespace: guestbook
    syncOptions:
    - CreateNamespace=true



