apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firstgit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/erkules/kubi.git 
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
