# Ab K8s 1.19
apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  rules:
  - host: argocd.YOURNAMESETC.zwerk.org
    DELETETHISLINE
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: argocd-server
            port:
              number: 80

