apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-gitlab
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/erkules/argocd.git
    targetRevision: HEAD
    path: kustomize
    kustomize:
      namespace: knuddeln2
      commonAnnotations:
        managed-by: fuchsschanz
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal:   true # Monitor die Resourcen und fixe wenn was futsch ist
