apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erkules/k8sworkshop.git
    targetRevision: HEAD
    path: Kustomize/simple 
  destination:
    server: https://kubernetes.default.svc
    namespace: red6
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
