apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/erkules/k8sworkshop.git
    targetRevision: HEAD
    path: Kustomize/simple 
  destination:
    server: https://kubernetes.default.svc
    namespace: red6
  syncPolicy:
    automated:
      selfHeal:   true # Monitor die Resourcen und fixe wenn was futsch ist
      prune:      true # Deletes in Git werden "durchgereicht"
      allowEmpty: false # Darf alles gelöscht werden?
    syncOptions:
    - CreateNamespace=true     # 
    - PruneLast=true
    - Validate=false           # Wenn zu.B. dir CRDs noch installiert werden .. aber auch .. doof
    - ApplyOutOfSyncOnly=true  # anstatt alles zu applyen nur die objekte mit delta
    - PrunePropagationPolicy=foreground # Wie gehe ich mit Cacardierenden deltes um? background,foreground,orphan.
    - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored bythe ignoreDifferences configuration
