---
# This secret optional because
# no credentials are needed
# Nowadays ArgoCD automatically checks if it is an OCI-Repo
apiVersion: v1
kind: Secret
metadata:
  name: helmrepo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: helm-oci
  url: docker.io/erkules
#    enableOCI: true   # from v2.10 replaced by type: helm-oci

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  source:
    repoURL: docker.io/erkules
    targetRevision: 2.1.0
    #path: ""
    chart: simple
    helm:
      releaseName: genau
      values: |
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-simple
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      #- ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true # sync stage
  ignoreDifferences: # diff calculation
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
