apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.helm.sh/stable
    targetRevision: 0.4.3
    path: ''
    chart: tomcat
    helm:
      releaseName: feuerbote
      values: |
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: feuerbote
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true

