#############################################################
#
# Einfachte Bsp. wir nutzen kubectl im Pod
# kubectl greift sich token etc. automatisch
# Aber damit es klappt brauchts noch das RoleBinding
#
#############################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ichdarfdas
---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: baba
#subjects:
#- kind: ServiceAccount
#  name: ichdarfdas
#roleRef:
#  kind: ClusterRole
#  name: admin
#  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  serviceAccountName: ichdarfdas
  containers:
  - name: kubectl
    image: erkules/kubectl:v1.30.2
    command:
    - sleep
    - "10000"

