apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  #https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md
  # name must match the spec fields below, and be in the form: <plural>.<group>
  # Pizza CRD ist sooooo der Klassiker
  # Wer sagt da der Plural heißt pizzen?!!!
  name: pizzas.linsenraum.de
spec:
  group: linsenraum.de
  # LIST of versions supported by this CustomResourceDefinition
  # Sprich hier wäre ein Array mit allen bekannten Versionen!!!eins11
  versions:
  - name: v1
    # wenn serve true via API verfügbar
    served: true  
    # 
    storage: true
    # Template für die CRD
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            # Noch mehr validation :)
            x-kubernetes-validations:
            - rule: "self.menge > 0"
              message: "get lost"
            properties:
              pizza:
                type: string
              menge:
                type: integer
    additionalPrinterColumns:
    - name: pizza
      type: string
      jsonPath: .spec.pizza
    - name: menge
      type: integer
      jsonPath: .spec.menge
  # bei mehreren versions kann eine conversion angegeben
  conversion:
    strategy: None
    #strategy: Webhook
    #webhookClientConfig
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    plural: pizzas
    # singular name to be used as an alias on the CLI and for display
    singular: pizza
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Pizza
