# Ist eine genamespacte Ressource!!
# nur host, welche hier enthalten sind kommen durch

apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - 'test.hallo'
        - 'pest.hallo'
        - 'cola.hallo'
        - 'bookinfo.hallo'
