apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: www
spec:
  hosts:
# Ziel vom curl
    - 'test.hallo'
  gateways:
    - gateway
  http:
    - route:
      - destination:
          host: www
          subset: hallo
          port:
            number: 80
      match:
      - headers:
          user-agent:
            regex: '.*k8s.*'
    - route:
      - destination:
          host: www
          subset: welt
          port:
            number: 80
