apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata:
  name: fanout
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    # muss nicht nicht für nginx noch ein use-regex rein?
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /www(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: www
            port:  
              number: 80
      - path: /web(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service: 
            name: web
            port:  
              number: 80

