apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  minReadySeconds: 4
  selector:
    matchLabels:
      app: mysqld
  template:
    metadata:
      name: mysqld
      labels:
        app: mysqld
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: <hostname>
      containers:
      #- name: exporter 
      #  image: prom/mysqld-exporter
      #  args:
      #  - --collect.auto_increment.columns 
      #  - --no-collect.auto_increment.columns
      #  - "--mysqld.username=root"
      - name: datenbank
        image: mariadb
        readinessProbe:
          tcpSocket: 
            port: 3306
        livenessProbe:
          tcpSocket: 
            port: 3306
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
        env:
        - name:  MYSQL_ALLOW_EMPTY_PASSWORD
          value: jajaja
      terminationGracePeriodSeconds: 5
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysqld


