apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "test"
  labels:
    cilium: enabled
    ccm:  enabled
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
      - name: hcloudPlacementGroups
        value:
          - name: control-plane
            type: spread
          - name: md-0
            type: spread
          - name: md-1
            type: spread
      - name: hcloudSSHKeyName
        value:
          - name: k8s
      - name: region
        value: fsn1
      - name: hcloudControlPlaneMachineType
        value: cx32
      # - name: hcloudControlPlaneMachineImageName
      #   value: ubuntu-22.04
      - name: hcloudControlPlanePlacementGroupName
        value: control-plane
    version: v1.29.4
    workers:
      machineDeployments:
        - class: hcloud-worker
          name: md-0
          replicas: 1
          failureDomain: fsn1
          variables:
            overrides:
              - name: hcloudWorkerMachineType
                value: cx22
              # - name: hcloudWorkerMachineImageName
              #   value: ubuntu-22.04
              - name: hcloudWorkerMachinePlacementGroupName
                value: md-0
