apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
 name: aws
spec:
 credentials:
   source: Secret
   secretRef:
     namespace: crossplane-system
     name: aws-provider
     key: creds
