# Schöner mit "Header"!!
#kind: Kustomization
#apiVersion: kustomize.config.k8s.io/v1beta1
namespace: jaja
helmCharts:
- name: tomcat
  releaseName: tomcat
  repo: https://charts.helm.sh/stable
  valuesInline:
    replicaCount: 3
    service:
      type: NodePort
  version: 0.4.2
resources:
- ns.yaml
patches:
- path: patch.yaml
