kind:        Deployment
apiVersion:  apps/v1
metadata:
  name: tomcat
spec:
  template:
    spec:
      tolerations:
      - key: "jaja"
        operator: "Exists"
      containers:
        - name: tomcat
          startupProbe:
            httpGet:
              path: /sample
              port: 8080
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 0
          readinessProbe:
            initialDelaySeconds: 0

