apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hallo
resources:
- ns.yaml
- nginxwithexporter.yaml
- podmonitor.yaml 
- keda.yaml
- wrk.yaml
- service.yaml
#- ingress.yaml
- networkpolicy.yaml
- alert.yaml
configMapGenerator:
- name: wrk
  files:
  - wrk.lua
- name: mynginxdashboard
  files:
  - dashboard.json
  options:
    labels:
      grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
