apiVersion: v1
kind: Pod
metadata:
  name: wrk
spec:
  containers:
  - name: wrk
    image: alpine:3
    command:
    - sh 
    - -c
    - "apk add wrk; sleep 3 ; wrk -d 600s -c 100 -t 12 --latency  -s /wrk/wrk.lua http://nginxwithexporter  ; sleep 5000"
    volumeMounts:
    - name: wrk
      mountPath: /wrk
  volumes:
  - name: wrk  
    configMap:
      name: wrk


