apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: database-password
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshPolicy: CreatedOnce

  target:
    name: database-credentials
    creationPolicy: Orphan
    immutable: true
    template:
      type: Opaque

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: database-password
