apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: database-password
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 32
      digits: 5
      symbols: 5
      symbolCharacters: "-_$@"
      noUpper: false
      allowRepeat: true

---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: database-credentials
spec:
  externalSecretName: database-credentials

  namespaceSelectors:
    - matchLabels:
        secrets.example.org/database-password: "true"

  refreshTime: 1m

  externalSecretSpec:
    refreshPolicy: CreatedOnce

    target:
      name: database-credentials
      creationPolicy: Orphan
      immutable: true
      template:
        type: Opaque

    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: database-password
