apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dontdeployme
spec:
  teamId: "k8s" <- must
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
