apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: simple-pipeline
spec:
  params:
    - name: pipelinename
      type: string
  tasks:
  - name: uno
    taskRef:
      name: task-einfach-env
    params:
    - name: welt
      value: "$(params.pipelinename): uno"
  - name: due
    taskRef:
      name: task-einfach-env
    params:
    - name: welt
      value: "$(params.pipelinename): due"
  - name: tres 
    taskRef:
      name: task-einfach-env
    params:
    - name: welt
      value: "$(params.pipelinename): tres"
  - name: after
    taskRef:
      name: task-einfach-env
    runAfter:
      - tres
    params:
    - name: welt
      value: "$(params.pipelinename): after"
