apiVersion: v1
data:
  flux.agekey: IyBjcmVhdGVkOiAyMDIyLTA2LTA3VDIzOjMyOjE0KzAyOjAwCiMgcHVibGljIGtleTogYWdlMXZ6dXpnYTJzYWU4M2ZoamZnaDg4d2xxendkbHZrZThxNWNrbmh1c3Bqa2twMno4cG5keXFwdzJqbnUKQUdFLVNFQ1JFVC1LRVktMVNINzg5MFM2M0U2TjZYOFZQM1dMR0tFTEFTOTdYUVNNU0czRFpGVDg2TkFRMFMzUVpYNlNaVjlUOE0K
kind: Secret
metadata:
  name: sops
  namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops
  path: Fluxv2/secret
  sourceRef:
    kind: GitRepository
    name: workshoprepo
  interval: 1m
  prune:    true
