---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-simple
  namespace: flux-system
spec:
  path: Fluxv2/simple
  sourceRef:
    kind: GitRepository
    name: workshoprepo
  interval: 1m
  prune:    true
