---
# Source: pxc-db/templates/cluster-ssl-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-db-pxc-db-ssl
  labels:
    app.kubernetes.io/name: pxc-db
    helm.sh/chart: pxc-db-1.13.0
    app.kubernetes.io/instance: my-db
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRS2xYR1RhaG5VdnBTTXNBUWI1eWlDakFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5dGVTMWtZaTF3ZUdNdFpHSXRZMkV3SGhjTk1qTXdPREUzTURBeU1qQTJXaGNOTWpRdwpPREUyTURBeU1qQTJXakFhTVJnd0ZnWURWUVFERXc5dGVTMWtZaTF3ZUdNdFpHSXRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGMlVsb0FRMHkyQ2t1ZDF3emlEM25DdnFJb3dHMlhOb1UKMzBIbFhLclRGVXlURktWR0pBRlVqTk82OHAzVC9ic2hLWGNFWlY1QXRReFFyVHQzTm9nZ3NoMUh0T1A4ZEFsdgpCbS93SVNDaXNhTXNiZnJLclM1VnJUd2RCOXcxMENHbDltU2tvcUs4TmhPQWpUZVBlNXhDSi8zMjZnZmxiY256CndkbzRiU2ZyUElpY1lVc0pDREdTcTUxRUtPNDhVb3lpdkljRGFObXZIbTlUYnRIeFNHbWowakxTV0dFRFRXWlMKS0JhZFNpdDRqblpvajRXbloxMm0vRUdsRzUyRE1ZaHRIS3ZrTXJiSmZpVU1SeVpxVUZwQ2pvT2dESjBmcEVhZQprUVNGMzc0dXlxV2pkM0d4aEcxMGhyVFBPekVQTTViYWlFeFJzSzZ5ZHZYMVVlN1hLS1F0QWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdkFad2JqcE9QL1dLVnpOZ3E1VUxCMjJ1OWlJdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRUt1MkFqUXQvVlo5akdPWWdLNnIzZEt2VlQ2M2d2V25MNnpUTi96CnprRmV0ejJNV2NGWjg1R3A3VEg5ZmptNGswNXlla002UDhLS2ZxQVZ1ZFpTOC8wQ0h6REpUYkgwUFNCcS9hZXUKSk9Eb0lCL0dtTVgraHpJS00wUzhadE9UK3NpVmZhMzhXRE9vN01OSUN6YWJucmdTaUVzSmhZTDF0Z01TTFhkNAprWjJkUXR3Umd3WlN5dXVyUTBMTnZXdTlDblZ6TU1QcU9CRU9kdGlFd1RmQXNYSnpLOStVOFFDclpHT3VpTVU0CmpSMGtwWlY4bWpPU3RTUmJlTDhhOG0yanNjdmh1K3h5QXZoMjFGODk5Tk1PelpNK2M2RGRxRy9iMzMvdkl6cHEKL0FrQW4zNUg2anNKZFE4K0Q4R041TmxnUTBWQWp2R1BVdUFEemNzZUlsdkE2Z2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjVENDQWxtZ0F3SUJBZ0lSQU9JdzFTY2R5VXZqUURRWHAyTVBoQnN3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXhNUGJYa3RaR0l0Y0hoakxXUmlMV05oTUI0WERUSXpNRGd4TnpBd01qSXdObG9YRFRJMApNRGd4TmpBd01qSXdObG93SURFZU1Cd0dBMVVFQXhNVmJYa3RaR0l0Y0hoakxXUmlMWEJ5YjNoNWMzRnNNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6Q29HM0Nzc1VTZm1JcklqMVZaK2gyWjAKYXpyM1daNlU3TUtVL3NUWGd5WVVaVTBlRlB4dTlhWDhmT1NOakVEcWVla1FOdWMrQVNaUGVYVFplVEJOdDdMQwpoaDFjVWlkeXVLQ2RSR2dBbEFXS3duMDZXOWdiUWROZVNqNURzb0p5cGJyMGRjVTlULzFuNzZBOGFhYkxFaFFFCldpNGVXQ3ozYXRYSWwwTnRMYjFaaUFSSzh6Y1VKaW94ak5Na1R1NXBadWNRQjFsdnp6TUxtaElRQ29NOVJQRmwKNDRBMlNWREE3YUtwaE8xTXplQ1JLNnJpZ3E2MElJeS9wcmpJRElQUGdPeEFobElvMTRpT3pqcXFiQ1ZvR0xjKwpQdGZoSy9wSnZBTG9oYWxTMnM1OGExVXJkS2xCUzJ3YU1mdEIrUVJ3c3lXbzRuYjk1NW9SaHlDNFNuUHJ2UUlECkFRQUJvNEdyTUlHb01BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlM4Qm5CdU9rNC85WXBYTTJDcgpsUXNIYmE3MklqQklCZ05WSFJFRVFUQS9naEJ0ZVMxa1lpMXdlR010WkdJdGNIaGpnaElxTG0xNUxXUmlMWEI0Cll5MWtZaTF3ZUdPQ0Z5b3ViWGt0WkdJdGNIaGpMV1JpTFhCeWIzaDVjM0ZzTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQ21HdzhpSFF5UlNBR2NoSnFBVUQ1UUxKSHU3eTM3Mm5hRFMyWHhGbzMwYzZ3ME5DaGlwU1hYQndVYQo2aS9TNW8wNmVqcyt2bEZGTkVlSmhSOUxhVEs2cWFvUndlUzhXd0pKaytxT01aK0dQa3RXeXBKTVJOQ3RGd1pjCktXY0NPcXhZWmpkOWpndkNEKzNyeUZOZFZxdnVvcHZjV002UGtsakIyeUVWVUNtT1QrV01BQmd5RkJMTWd6UksKbEZnQmlibW9HUHN1YTh1dG5BVzJwRVREZ1dCeTAxMnFvR3lxeURRbkN0bFN4aDVHZk5KQzIydTBtTUY3S3VZVgpsNy9ud0NZVXZwNkFSdi9YL1VtUzR6bGhKOFpaVi9lRzhhVXhLWWQzVmxYY205ck5jRkhJYVdQOXhsczZrZk1KCmJIeXg5Q1hGUTI1U2huM3F0ZjBUa0s2dlFrZC8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBekNvRzNDc3NVU2ZtSXJJajFWWitoMlowYXpyM1daNlU3TUtVL3NUWGd5WVVaVTBlCkZQeHU5YVg4Zk9TTmpFRHFlZWtRTnVjK0FTWlBlWFRaZVRCTnQ3TENoaDFjVWlkeXVLQ2RSR2dBbEFXS3duMDYKVzlnYlFkTmVTajVEc29KeXBicjBkY1U5VC8xbjc2QThhYWJMRWhRRVdpNGVXQ3ozYXRYSWwwTnRMYjFaaUFSSwo4emNVSmlveGpOTWtUdTVwWnVjUUIxbHZ6ek1MbWhJUUNvTTlSUEZsNDRBMlNWREE3YUtwaE8xTXplQ1JLNnJpCmdxNjBJSXkvcHJqSURJUFBnT3hBaGxJbzE0aU96anFxYkNWb0dMYytQdGZoSy9wSnZBTG9oYWxTMnM1OGExVXIKZEtsQlMyd2FNZnRCK1FSd3N5V280bmI5NTVvUmh5QzRTblBydlFJREFRQUJBb0lCQVFDQVo0WTgvcUkyd0lOTApHd0xTY0QzUDVxNGRxczVhZlJSbys5QTlrNHQvbm5tQlpNa2dwY3Nia0RPR1VUQjlIMjdaRWEzeStlalRURWI3CnVuUDBkbDdLeEJEM3pJdDkxL1dkRE5jY2FOVEVRK0FMaGpzbi9IallJNW5QMCswNzNqTkE3SjVIVzYrK0dVQS8KUTJYN2hMMS9OenV0aEFmdHFRcExGUDI5dE5oN3hOVnBhKzNvV2FFaXBmdStnKzNIelZSMlEyaExwSTJNajNyOQp6bklML2wrbXh6UVdVeERqaVN5aEp0K3c3eXdwd2U2VXRISWdhcERFWThzckFuTDU4c3dLclc1YmZseXpIdXd1CllqRVdJd3pkaFdMZWlKZlJNd0I3R2hEZUh5VG5SVmp1clBjR2M2b2dwTkxhdXFlSllyVzk5TmQzUWVmb1Y1L20KTjBReU9aZEJBb0dCQU9nZ0FSUzh6djBJUElWeldCbGxrYW9yRitPRldWYTkrTmJGbitFd2tnU0VLdksxYzU2YgpNL0cydEFrSHJXZDBVMU1GS09GOXR3UmJqY1AzRVhycVdzTlNPQTIwNTZIR3dONHdYTVNJK2dMa1Z2MEFKL3U2CjViSkhLclE5Q0tMNUk0WU9EdVBsUjg5RG9JYmUrQTd5a2pXNjd5ZDlEd21vNDIxeDg5VTdHVm5WQW9HQkFPRXAKeThwQTJBQklzN1c4V0NYbjNXS1ZEM2NreFJNaW5JY0JGTFhQbmYrRTBvNUdVR3VSRlI2TTRhRG1mbWhrd1d5cQplNDFLLzBHcloxcC9GanBKZzQxMWZJRmVFMXpveU1tUVdYOXVRVTBUOTFBOUNkQ3ZybFp6NWFnOVdVRnN0eVdYCmU4Z3FpVnBhU0Q1TTFGcnZvRHZKQ0EwNkszcE1qZDhKa1BFUC9SWkpBb0dBV09Nb2h0Qm1VdTY4ZmozVkZxU1cKU3h1RllsTEdDemxqK0pwa3hzN2FtM0FoSWgvcHptcVFVWmN0Q2VndXR0Y01zVlhnZWJpeVJMRHFjSWhENFZXcwp1KzdZR0NlV0s1VDRkaHorNlNPcTJVQ25MdXJJWk5VRThHZmdLblRVd2RPMWpyZ0RhN0Y0OWgxbmN6NGVyMXFrCk1uOEs1WXcySGZUV1lpcW92SmFNOXFFQ2dZQWZoYkZ4SEVqaEtVeDNlZW5CVE1leW9IbXN6V29GdHNmQklzYWEKZVhsK0owTXZCZXNHVkNabnc0Tm0rajNpTVpEZXZMTlZZWldBeFJWUUZ4Q3VrbEluZ0xZd2lsSWRwTDFQY3JVRQo0Uk9sVGRGRzIzUy9VWWtQczJRSWZLWTlRWklXWWpIRElTbGZpOW9uVnF3NEd1b00xS1VhN1BUZlIwNXBWamFECmVTQ09lUUtCZ0JScmwrS2RzOElaR2NwZ2VWVC9UVjJwT05GbTNMbk1ETFJFT05Md3RWV0F4SU42UDlHSWpEem8KUlliV05EbFlidWNJdzh0YXJsNUh5M2svclMxSDgxanlhSTU1RFdlQnZXdkVWQkJXQmlITkdnczhWc0xheWxDOQp1SkVmYzlxVWxiK0hWZWhMN1dyVUV2NXBnTTlHZW9oSUZpRE9WOHk3dWpkWDV3MmxrYWcrCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: pxc-db/templates/cluster-ssl-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-db-pxc-db-ssl-internal
  labels:
    app.kubernetes.io/name: pxc-db
    helm.sh/chart: pxc-db-1.13.0
    app.kubernetes.io/instance: my-db
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRS2xYR1RhaG5VdnBTTXNBUWI1eWlDakFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5dGVTMWtZaTF3ZUdNdFpHSXRZMkV3SGhjTk1qTXdPREUzTURBeU1qQTJXaGNOTWpRdwpPREUyTURBeU1qQTJXakFhTVJnd0ZnWURWUVFERXc5dGVTMWtZaTF3ZUdNdFpHSXRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGMlVsb0FRMHkyQ2t1ZDF3emlEM25DdnFJb3dHMlhOb1UKMzBIbFhLclRGVXlURktWR0pBRlVqTk82OHAzVC9ic2hLWGNFWlY1QXRReFFyVHQzTm9nZ3NoMUh0T1A4ZEFsdgpCbS93SVNDaXNhTXNiZnJLclM1VnJUd2RCOXcxMENHbDltU2tvcUs4TmhPQWpUZVBlNXhDSi8zMjZnZmxiY256CndkbzRiU2ZyUElpY1lVc0pDREdTcTUxRUtPNDhVb3lpdkljRGFObXZIbTlUYnRIeFNHbWowakxTV0dFRFRXWlMKS0JhZFNpdDRqblpvajRXbloxMm0vRUdsRzUyRE1ZaHRIS3ZrTXJiSmZpVU1SeVpxVUZwQ2pvT2dESjBmcEVhZQprUVNGMzc0dXlxV2pkM0d4aEcxMGhyVFBPekVQTTViYWlFeFJzSzZ5ZHZYMVVlN1hLS1F0QWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdkFad2JqcE9QL1dLVnpOZ3E1VUxCMjJ1OWlJdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRUt1MkFqUXQvVlo5akdPWWdLNnIzZEt2VlQ2M2d2V25MNnpUTi96CnprRmV0ejJNV2NGWjg1R3A3VEg5ZmptNGswNXlla002UDhLS2ZxQVZ1ZFpTOC8wQ0h6REpUYkgwUFNCcS9hZXUKSk9Eb0lCL0dtTVgraHpJS00wUzhadE9UK3NpVmZhMzhXRE9vN01OSUN6YWJucmdTaUVzSmhZTDF0Z01TTFhkNAprWjJkUXR3Umd3WlN5dXVyUTBMTnZXdTlDblZ6TU1QcU9CRU9kdGlFd1RmQXNYSnpLOStVOFFDclpHT3VpTVU0CmpSMGtwWlY4bWpPU3RTUmJlTDhhOG0yanNjdmh1K3h5QXZoMjFGODk5Tk1PelpNK2M2RGRxRy9iMzMvdkl6cHEKL0FrQW4zNUg2anNKZFE4K0Q4R041TmxnUTBWQWp2R1BVdUFEemNzZUlsdkE2Z2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLekNDQXhPZ0F3SUJBZ0lRQ0Y5SUtSbCt4Ymt1RXhLejhrTjhBVEFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5dGVTMWtZaTF3ZUdNdFpHSXRZMkV3SGhjTk1qTXdPREUzTURBeU1qQTJXaGNOTWpRdwpPREUyTURBeU1qQTJXakFiTVJrd0Z3WURWUVFERXhCdGVTMWtZaTF3ZUdNdFpHSXRjSGhqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBOW5oYlhNT2h5OTR2R3hpb0djbStIb2VyY21UMHB0TGIKWTNlZ3NoZnNxMUpCZ29OKzdkdncvaDNpWElobWlDcTAybTVyOHFZRzJ0Sll1b3ZBaHJVdzYxS3o0UU9GbkYrbwpvenQ1VHl2Ym5KZTA0ZGtrb3hTY0lxT3JJYVZIY2h5WVpaRFVKRWlqdnlmMEdHZE4wdC9tOUZGTC9WQVZ1Skx6Cm1GVmd6cXpNbVBnNGVOc1NrNmJuMGovVTRvdjB6S1RPQ2t0UnV0SytBaWZWYmZ5dTdPUWVqVXF5b0NySlVuNlcKL1JtSWZYeVR5bXUybmRQY1RDeEFVNi81TlJjeVk0SU1rTEtCMlQ0V0NtaTAvWStlZFMrVE04Q1oyRFhTSnpEbgpQSlZYWnozQzFrZ0FpTnZHS2ZQdENTTGkyUHpyK0hYMlhFbm01cTlaTUFoTkJyUTViSHRSTHdJREFRQUJvNElCCmFqQ0NBV1l3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZMd0djRzQ2VGovMWlsY3pZS3VWQ3dkdApydllpTUlJQkJBWURWUjBSQklIOE1JSDVnaEJ0ZVMxa1lpMXdlR010WkdJdGNIaGpnaElxTG0xNUxXUmlMWEI0Cll5MWtZaTF3ZUdPQ00yMTVMV1JpTFhCNFl5MWtZaTFvWVhCeWIzaDVMWEpsY0d4cFkyRnpMbVJpTVM1emRtTXUKWTJ4MWMzUmxjaTVzYjJOaGJJSWhiWGt0WkdJdGNIaGpMV1JpTFdoaGNISnZlSGt0Y21Wd2JHbGpZWE11WkdJeApnaDF0ZVMxa1lpMXdlR010WkdJdGFHRndjbTk0ZVMxeVpYQnNhV05oYzRJcWJYa3RaR0l0Y0hoakxXUmlMV2hoCmNISnZlSGt1WkdJeExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2doaHRlUzFrWWkxd2VHTXRaR0l0YUdGd2NtOTQKZVM1a1lqR0NGRzE1TFdSaUxYQjRZeTFrWWkxb1lYQnliM2g1TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBUwpTdlluajJadnNwK3UvcUV6NFBBVHBnckhxWk9aQmowZTFMSVhXbmsvbE9ybHZ5WUFxOHBoM3NtT3hJenRucmUvClVOUWtzbWV1WE5keURIRGVMbWxqZkcvTmV2Zm1DYktoTjl3K011NDRiaGFkQnc1SkExelZIeTNyaE1zd1dOaXUKdFVEcG1YOUZPM2cxd0VZaStyU0tWb05RTHlJQy91ZVBEVEpRa3ZDOXNRcFlrTWN3eUdhbVhBZ2lodUk3VG55eApocXhlNzlwOTFnVDMrc0hPbjV1TnR5NVF6VXc1NWVVaUFvZU83SFNLYmZpRSs0TzlnblZCVWpJcTBoZ3BMTWpGCkUweUdGekl1SkZ0eXRCektWOC9LMnVUck81OWtKQ3FMSjIvcnVUbWhIci90SUdib0Z1aTM1RHVMTHlrdUZHMnMKL3Z6K1ppWnVkVkcxSEtwaXZaWEQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBOW5oYlhNT2h5OTR2R3hpb0djbStIb2VyY21UMHB0TGJZM2Vnc2hmc3ExSkJnb04rCjdkdncvaDNpWElobWlDcTAybTVyOHFZRzJ0Sll1b3ZBaHJVdzYxS3o0UU9GbkYrb296dDVUeXZibkplMDRka2sKb3hTY0lxT3JJYVZIY2h5WVpaRFVKRWlqdnlmMEdHZE4wdC9tOUZGTC9WQVZ1Skx6bUZWZ3pxek1tUGc0ZU5zUwprNmJuMGovVTRvdjB6S1RPQ2t0UnV0SytBaWZWYmZ5dTdPUWVqVXF5b0NySlVuNlcvUm1JZlh5VHltdTJuZFBjClRDeEFVNi81TlJjeVk0SU1rTEtCMlQ0V0NtaTAvWStlZFMrVE04Q1oyRFhTSnpEblBKVlhaejNDMWtnQWlOdkcKS2ZQdENTTGkyUHpyK0hYMlhFbm01cTlaTUFoTkJyUTViSHRSTHdJREFRQUJBb0lCQVFESVJkSlBWWFB5V1k5RApZRXl2Nzd0NXlWb3A4UmpQT2NVbFZQNlIyRmpxZVVOY0R3ZWp0YlZrZDlvSXdKazRDaU84M2o3L0E2UE1TV0hwCjYwYzg3cHhhaTNBNDVnaTZvUXhCMzBEYWNWUFpNWGk4a0JweUhYd2x0WUtJSzJvYnNscXZKUGtNcHEzUDFXSkcKTmlNSnVBQk9CSVZQeDdSdXI1SWE5VDFka3hJSk5RbE5iQlIyQmk5Z281Qk9UTFlFUHNQektCeXJUZmJaMTMxUQpvYUxxdTJtaVByS3RmbkdUZ0FBTWhYb0Jja3M2c0l6OHhPM0tzVS9pbmkxR0Uwc0cwQzdLd1RrR3hQVy8ybVpPCjRqcDkwcWR6eUc2clViWFVUVS9TQzhFemNNSGZPd0tlV21MTHNCUzRQME1JTVpqM3hsTmpvRWFNSnYrcWNrQUEKWDNhN05YaDVBb0dCQVB0bWdUM2lZNDcvZXBSWmhscC80ZWZ2V3lqalNQZmQrRXJrWmUwZUNWWXVnSStrQnpoVwpyRkgwWHU5ckQrS0h6WTc4aldJMkt3Vlo1WVVKS1dydCs4VTNlUDZZSFM4Y3ZoMVhBbUFjY0xTK0RVNk1DS05LCnBwRUJyZGxoNGhzV3IzTzBVR2l0MUZLWTh5dmRGZzE2ellmeWI5a3dTeThmZloyeWpaSFJmY05iQW9HQkFQcjYKd29ydk56ZGp5blFycENKb1VBc1djK0l5a2VJUUQ1c2N1K1VwMitHOVh0Ymo0c1RxcEc5T2RKVXU2Nk9INUNVZApQK2hTbHdmazgzNWxPQU1XYS8vWnloaXAycldFQWQ4elFKWGhwN1RVN3E5M25PY1I4WDZ0THgwNTUvdGdEK29sCmk5L0FTVEdOWVg5S04rZHJ3UjJlVUpiMUJ1aldmQzhnVC9HUHhQVzlBb0dBWTJNWjB4Sk9FN2xTaDVXQTlRUTcKbGdyZGVpT290RDB2ck1Qd3U3WTFNTG4vbjBuVWhPUlhDYXRYWU1WdHFUdlEreWRDNmNIS2Jqb2s3OXc0WUlxbgpEMGVuOE5iSUt0anRIQUpLOFI0dFBIY3FJWlJnMGRWd1ZrRllybWp4RDQ1L1hIbTdsRGFzaXQ3bXU3K1N1VStFCk02dVhwa0JlYU1uRlNuUE5YZ2w0ODZNQ2dZQXZjdFR3dTBUdkhkaWFtZDJQKzdTV1JBcG9pekwxVUNBRExTMkEKcDZkQVNETHo0V1Z2NFFSeFhwMi96bjBTRDVEY1MybFhuTFdjOG5YdVFXaVRmTnV5SlJTR0VTYWVCblRzSTU1awpONk1qRnRhQktkWHFBWVJzZElWaHV4N1djVlRRNllSR0t1NHJoaFVXb1l0c0h2MEZnbmF0ODJqNUFBTytUUmVRCkRhUW82UUtCZ1FDU1JSb2NyR3p3bnNTQkpoVVZXNW9LMllybzJyT2dZZC9xMHVLWk9LRHpvbzQrR1g4MktMM3gKazBjekd6Q2NWZE9nelIvdXZkWDhpTWt3L05rUld3ZHJtaG56YVU0UE84SnladWtZdEdZbzRNVFhkWWFsbURYRwovUWRLNWJaRTJSdS9adlZlVlE0ZnZpczNDSXZtZ05MdUpLV1IxVEVIRkV2bHhuTEFDWHdKWVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: pxc-db/templates/cluster.yaml
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-db-pxc-db
  labels:
    app.kubernetes.io/name: pxc-db
    helm.sh/chart: pxc-db-1.13.0
    app.kubernetes.io/instance: my-db
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/managed-by: Helm
  finalizers:
    - delete-pxc-pods-in-order
spec:
  crVersion: 1.13.0
  secretsName: my-db-pxc-db-secrets
  sslSecretName: my-db-pxc-db-ssl
  sslInternalSecretName: my-db-pxc-db-ssl-internal
  vaultSecretName: my-db-pxc-db-vault
  logCollectorSecretName: my-db-pxc-db-log-collector
  initImage: percona/percona-xtradb-cluster-operator:1.13.0
  enableCRValidationWebhook: false
  pause: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: 0 4 * * *
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.32-24.2
    autoRecovery: true
    readinessDelaySec: 15
    livenessDelaySec: 300
    annotations:
      {}
    labels:
      {}
    resources:
      requests:
        cpu: 600m
        memory: 1G
      limits:
        {}
    sidecars:
      []
    sidecarVolumes:
      []
    sidecarPVCs:
      []
    sidecarResources:
      requests:
        {}
      limits:
        {}
    nodeSelector:
      {}
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    tolerations:
      []
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      emptyDir: {}
    gracePeriod: 600
    readinessProbes:
      failureThreshold: 5
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 15
    livenessProbes:
      failureThreshold: 3
      initialDelaySeconds: 300
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
  haproxy:
    enabled: true
    size: 3
    image: percona/percona-xtradb-cluster-operator:1.13.0-haproxy
    replicasServiceEnabled: true
    annotations:
      {}
    labels:
      {}
    resources:
      requests:
        cpu: 600m
        memory: 1G
      limits:
        {}
    sidecars:
      []
    sidecarVolumes:
      []
    sidecarPVCs:
      []
    sidecarResources:
      requests:
        {}
      limits:
        {}
    nodeSelector:
      {}
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    tolerations:
      []
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      emptyDir: {}
    gracePeriod: 30
    readinessDelaySec: 15
    livenessDelaySec: 300
    readinessProbes:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbes:
      failureThreshold: 4
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
  proxysql:
    enabled: false
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.13.0-logcollector
    resources:
      requests:
        cpu: 200m
        memory: 100M
      limits:
        {}
  pmm:
    enabled: false
