apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: validateion
  namespace: webhook
spec:
  secretName: validation
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: check.webhook.svc.cluster.local
  dnsNames:
  - check.webhook.svc.cluster.local

