apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "webhook-check-example"
webhooks:
- name: "webhook-check-example.linsenraum.de"
  # Fail/Ignore
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: k8scamp
      operator: In
      values: ["spielen"]
  matchPolicy: Equivalent
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["DELETE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "webhook"
      name: "check"
    # base64 -w encodiertes pem
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVxZ0F3SUJBZ0lVZllpSXBBanYwblJ4am42a2xlMnBJbnJoZDlRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZWXhEREFLQmdOVkJBWVRBMGRGVWpFU01CQUdBMVVFQ0JNSlRtOUNiM0prWlhKek1SSXdFQVlEVlFRSApFd2xHY21GdWEyWjFjblF4RnpBVkJnTlZCQW9URGt0MVltVnlibVYwWlhORFlXMXdNUmN3RlFZRFZRUUxFdzVMCmRXSmxjbTVsZEdWelEyRnRjREVjTUJvR0ExVUVBeE1UU3poeklGZGxZbWh2YjJzZ1VtOXZkQ0JEUVRBZUZ3MHkKTVRBME1qQXlNekk1TURCYUZ3MHlOakEwTVRreU16STVNREJhTUlHR01Rd3dDZ1lEVlFRR0V3TkhSVkl4RWpBUQpCZ05WQkFnVENVNXZRbTl5WkdWeWN6RVNNQkFHQTFVRUJ4TUpSbkpoYm10bWRYSjBNUmN3RlFZRFZRUUtFdzVMCmRXSmxjbTVsZEdWelEyRnRjREVYTUJVR0ExVUVDeE1PUzNWaVpYSnVaWFJsYzBOaGJYQXhIREFhQmdOVkJBTVQKRTBzNGN5QlhaV0pvYjI5cklGSnZiM1FnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEeXJkdzVLOGdaR3ZDREx5QmNXTXpaM3FlZlp5ckROMVFaakQ3TFBQWnlSbEtKbHptOHRrRjg0ODdiCjZ4WUZRL1Q0WENjUit4R0FpZmY3dG9qdzBvcFkyQmlLMUJrUy8rQ3hXd1BYVzZ5bk9PNEZ1QTRDRktlY3VxRWgKbHBRWnNTQnQ4Z3I0Y1VnM1JoVVB2Y21vYXFpYUE0YjFOeGJQcVpRU1o2bGovOVlpSHNudW40RnR6Nm1iRUcvTQpMYmVnM0JtNzhQUDNnQjc1S2Z5YnhBeVdoalB2NWZ5UEhVTkdyaVNIR1VidGtLVWF0ZFRGM0Fva2R3MzBzc1NzCklDT20rdlAyVUU4bnJsdlVmK2JHSjNQOGkvbnYvenFMaTRCQVNIQ1prczNPVCtHVW1WYWVMNkt5T05qaE12eE4KaFdUb2pEcEpoMEVscjlWaWNqYVpBcmFiSWw4ckFnTUJBQUdqWmpCa01BNEdBMVVkRHdFQi93UUVBd0lCQmpBUwpCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUNNQjBHQTFVZERnUVdCQlIzWUhyczg5YVEyNlFSS0ZlT29lYk5Nc1ArCnN6QWZCZ05WSFNNRUdEQVdnQlIzWUhyczg5YVEyNlFSS0ZlT29lYk5Nc1Arc3pBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUF6SjZBakZOZ005UkxRcXNsWEZ5dGNMeGdGRjJLZHJkOVkvY0x3amxUaTNTY3NWc2toTzJxaGZiMAp6emc4d3VJZTBmTGRBZFNSNjNmN2VnV3FCcEppbUM1RzBpcmovYWpxMENjVDVvbnk5d1hycW9GSlMvMHFFWXlZCjZGN3I2L0w2bkJVeXEvUWh3aG5yQ2JYeVgrYlM5Qkt5VDJrelZKSGtCUmRFMDlxYncxV0IzWDVzMy9xK0s2aFAKRy8wMlROalljZXpRQnErWGt2STRFNGFuWERpS2hhR2ZSY21UV1hhR1RvOXBxN0FQTExCWVJ1T1g1Vzk5bGJCbQpTUmFoTGYwVWQ4TkkwVjAwK2ZGSjFFTzN0S0duQ1dKUHpKeml1TFFneHhoeDBhbTlDVUw3VXQrUk5kSjlYOWdICjVUZXUva3N0MCtQbVR6cnBDZFRCNnJwb1FaZXB5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
