apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
spec:
  secretName: client-cert-secret
  duration: 2160h # 90 days
  renewBefore: 1h
  commonName: client.cert-manager-bsp1.svc.cluster.local
  dnsNames:
    - client.cert-manager-bsp1.svc.cluster.local
  usages:
    - client auth
  issuerRef:
    name: ca-issuer

