apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobbisetti
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
  - name: workers
    replicas: 4                   # Wie viele Jobs
    template:                     # Jobtemplate
      spec:
        parallelism: 2 
        completions: 2 
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: hallo
              image: alpine
              command:
              - sleep
              - "5"
