apiVersion: v1
kind: Pod
metadata:
  name: docker-compose-runner
spec:
  containers:
    - name: dind
      image: docker:28.2.2-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: docker-sock
          mountPath: /var/run/

    - name: compose
      image: docker/compose:v1.25.2
      command: ["sleep", "3600"]
      volumeMounts:
        - name: compose-files
          mountPath: /compose
        - name: docker-sock
          mountPath: /var/run/

  volumes:
    - name: docker-sock
      emptyDir: {}
    - name: docker-graph-storage
      emptyDir: {}
    - name: compose-files
      configMap:
        name: my-compose-configmap # configmap mit docker-compose.yml optional
        optional: true
