# Wir provozieren einen Restart wegen Memory
# kubectl exec -ti pod-ressources-stress --  sh 
# stress   --vm 1 --vm-bytes 150m --vm-hang 0
# Container wird abgeschossen

apiVersion: v1
kind: Pod
metadata:
  name: pod-ressources-stress
spec:
  containers:
  - name: stress
    image: jess/stress
    command:
    - sleep
    - "5000"
    resources:
      requests:
        cpu: 10m
        memory: 100M
        ephemeral-storage: "1Gi"
      limits:
        cpu: 10m
        memory: 100M
        ephemeral-storage: "1Gi"
       
