apiVersion: v1
kind: Pod
metadata:
  name: www-liveness
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname
    livenessProbe:
      exec:
        command:
        - cat 
        - /etc/issue
      timeoutSeconds: 1
      initialDelaySeconds: 5
      failureThreshold: 3
      periodSeconds: 5

