# Achtung
# securityContext kann auf Pod und/oder Container Ebene gesetzt werden
# Zwar nicht alles überall, aber nicht scope
apiVersion: v1
kind: Pod
metadata:
  name: pod-min-priv
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: ping
    image: cgr.dev/chainguard/wolfi-base
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true            
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    command:
    - sleep
    - "5000"

