# ausrollen 
# kubectl get pods readinessgate -o wide # Nach READINESS GATES schauen
# kubectl patch pod readinessgate --type='merge' -p   '{"status":{"conditions":[{"type":"linsenraum.de","status":"True"}]}}' --subresource status
# kubectl get pods readinessgate -o wide # Nach READINESS GATES schauen
apiVersion: v1
kind: Pod
metadata:
  name: readinessgate
spec:
  readinessGates:
  - conditionType: "linsenraum.de"
  containers:
  - name: meinserver
    image: erkules/nginxhostname

