apiVersion: v1
kind: Pod
metadata:
  name: www
spec:
  containers:
  - name: meinserver
    image: erkules/nginxhostname:v2
    ports:
    - name:          nicht-notwendig
      containerPort: 80
    - name:          nerv #prometheus-operator will benamste Ports
      containerPort: 8080

