apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wwwds
spec:
  selector:
    matchLabels:
      app: wwwds
  updateStrategy:
    type: RollingUpdate #OnDelete
  template:
    metadata:
      name: wwwds
      labels:
        app: wwwds
    spec:
      #tolerations:
      #- key: node-role.kubernetes.io/master
      #  operator: Exists
      #  effect: NoSchedule
      containers:
      - image:  erkules/nginxhostname:v2
        name: www
