apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: demo-nightly
spec:
  cluster:
    name: baked-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
